services:
  app:
    image: que8581/tyrellsys-test-03:latest
    container_name: web_app_tyrell
    environment:
      - MYSQL_USER=tyrell
      - MYSQL_PASSWORD=tyrell123
      - MYSQL_DATABASE=tyrellsys
      - MYSQL_ROOT_PASSWORD=root123
    ports:
      - 8581:80
    depends_on:
      - db
  db:
    image: que8581/my-mysql:5.7.44
    container_name: mysql_db_tyrell
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: tyrellsys
      MYSQL_USER: tyrell
      MYSQL_PASSWORD: tyrell123
    ports:
      - 33069:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: